version: "3.7"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5454:5454"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=smart-pizza
