import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col antialiased">
          <Header />
          <div className="flex flex-1 flex-col gap-4 p-8 pt-6">
            <ThemeProvider attribute="class" defaultTheme="system">
              {children}
            </ThemeProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
